"""Authoritative schema discovery and field mappings for TEJ datasets."""

from __future__ import annotations

from typing import Any, Mapping


# Formal schema registry for entitled TEJ trial datasets
TEJ_TABLE_SCHEMAS: dict[str, dict[str, Any]] = {
    "TRAIL/TASALE": {
        "cname": "試用月營收資料庫",
        "category": "fundamental_revenue",
        "priority": 1,
        "frequency": "monthly",
        "entity_field": "coid",
        "period_date_field": "mdate",
        "announcement_date_field": "annd_s",
        "update_date_field": "annd_e",
        "pit_safe": True,
        "pit_rationale": "Authoritative announcement date 'annd_s' provided for every monthly release.",
        "key_columns": {
            "coid": {"type": "str", "cname": "公司代碼", "description": "Security identifier"},
            "mdate": {"type": "date", "cname": "資料年月", "description": "Period start/end date"},
            "annd_s": {"type": "date", "cname": "公告日期", "description": "Announcement publication timestamp"},
            "annd_e": {"type": "date", "cname": "公告截止日", "description": "Announcement revision timestamp"},
            "d0001": {"type": "float", "cname": "單月營收", "unit": "thousand NTD", "absorb_field": "revenue"},
            "d0002": {"type": "float", "cname": "上月營收", "unit": "thousand NTD", "absorb_field": "revenue_last_month"},
            "d0003": {"type": "float", "cname": "去年同期營收", "unit": "thousand NTD", "absorb_field": "revenue_last_year"},
            "d0004": {"type": "float", "cname": "營收月增率", "unit": "%", "absorb_field": "revenue_mom"},
            "d0005": {"type": "float", "cname": "營收年增率", "unit": "%", "absorb_field": "revenue_yoy"},
            "d0006": {"type": "float", "cname": "累計營收", "unit": "thousand NTD", "absorb_field": "cumulative_revenue"},
            "d0007": {"type": "float", "cname": "累計營收年增率", "unit": "%", "absorb_field": "cumulative_revenue_yoy"},
        },
    },
    "TRAIL/TAIM1AA": {
        "cname": "試用財務比率年報/季報公告日",
        "category": "fundamental_filing_dates",
        "priority": 2,
        "frequency": "quarterly",
        "entity_field": "coid",
        "period_date_field": "mdate",
        "announcement_date_field": "a0003",
        "pit_safe": True,
        "pit_rationale": "Authoritative financial report preparation/publication date 'a0003' provided per quarter.",
        "key_columns": {
            "coid": {"type": "str", "cname": "公司代碼"},
            "mdate": {"type": "date", "cname": "財報年月"},
            "a0003": {"type": "date", "cname": "財報發布/公告日", "description": "PIT filing announcement timestamp"},
            "a0004": {"type": "date", "cname": "會計期初日"},
            "a0005": {"type": "date", "cname": "會計期末日"},
            "curr": {"type": "str", "cname": "幣別"},
            "merg": {"type": "str", "cname": "合併報表註記 (Y/N)"},
        },
    },
    "TRAIL/TAIM1AQ": {
        "cname": "試用財務比率季報",
        "category": "fundamental_ratios",
        "priority": 3,
        "frequency": "quarterly",
        "entity_field": "coid",
        "period_date_field": "mdate",
        "announcement_date_field": "a0003",
        "pit_safe": True,
        "pit_rationale": "Joined with filing announcement dates from TAIM1AA/TAIM1AQA for strict PIT as-of join.",
        "key_accounting_codes": {
            "R535": {"name": "Recurring EPS", "unit": "NTD/share", "absorb_field": "eps"},
            "R103": {"name": "ROE After Tax", "unit": "%", "absorb_field": "roe"},
            "R11V": {"name": "ROA Comprehensive Income", "unit": "%", "absorb_field": "roa"},
            "R105": {"name": "Gross Margin Ratio", "unit": "%", "absorb_field": "gross_margin"},
            "R501": {"name": "Operating Profit Margin", "unit": "%", "absorb_field": "operating_margin"},
            "R504": {"name": "Debt / Equity Ratio", "unit": "%", "absorb_field": "debt_ratio"},
            "R406": {"name": "Current Ratio", "unit": "%", "absorb_field": "current_ratio"},
            "R401": {"name": "Revenue Growth Rate YoY", "unit": "%", "absorb_field": "revenue_growth_yoy"},
        },
    },
    "TRAIL/TAIM1A": {
        "cname": "試用財務資料庫 (資產負債/損益/現金流)",
        "category": "fundamental_statements",
        "priority": 4,
        "frequency": "quarterly",
        "entity_field": "coid",
        "period_date_field": "mdate",
        "announcement_date_field": "0003",
        "pit_safe": True,
        "pit_rationale": "Quarterly balance sheet and income statements with announcement date mapping.",
        "key_accounting_codes": {
            "0010": {"name": "Total Assets", "unit": "thousand NTD", "absorb_field": "total_assets"},
            "0100": {"name": "Total Current Assets", "unit": "thousand NTD", "absorb_field": "current_assets"},
            "0112": {"name": "Cash and Cash Equivalents", "unit": "thousand NTD", "absorb_field": "cash_and_equivalents"},
            "2000": {"name": "Total Equity", "unit": "thousand NTD", "absorb_field": "book_value"},
            "200D": {"name": "Book Value Per Share", "unit": "NTD/share", "absorb_field": "book_value_per_share"},
            "3100": {"name": "Operating Revenue", "unit": "thousand NTD", "absorb_field": "financial_revenue"},
            "3295": {"name": "Gross Profit", "unit": "thousand NTD", "absorb_field": "gross_profit"},
            "3395": {"name": "Operating Income", "unit": "thousand NTD", "absorb_field": "operating_income"},
            "7000": {"name": "Pre-Tax Income", "unit": "thousand NTD", "absorb_field": "pretax_income"},
            "8000": {"name": "Net Income", "unit": "thousand NTD", "absorb_field": "net_income"},
            "C001": {"name": "Cash Flows from Operating Activities", "unit": "thousand NTD", "absorb_field": "operating_cash_flow"},
        },
    },
    "TRAIL/TATINST1": {
        "cname": "試用三大法人買賣超資料庫",
        "category": "institutional_flow",
        "priority": 5,
        "frequency": "daily",
        "entity_field": "coid",
        "period_date_field": "mdate",
        "announcement_date_field": "mdate",
        "pit_safe": True,
        "pit_rationale": "Daily market close data available at end of day post-close.",
        "key_columns": {
            "coid": {"type": "str", "cname": "公司代碼"},
            "mdate": {"type": "date", "cname": "交易日期"},
            "qfii_ex1": {"type": "float", "cname": "外資買賣超張數", "unit": "1000 shares", "absorb_field": "foreign_net_buy"},
            "qfii_p": {"type": "float", "cname": "外資買賣超金額", "unit": "million NTD"},
            "fund_ex": {"type": "float", "cname": "投信買賣超張數", "unit": "1000 shares", "absorb_field": "trust_net_buy"},
            "dlr_ex": {"type": "float", "cname": "自營商買賣超張數", "unit": "1000 shares", "absorb_field": "dealer_net_buy"},
            "ttl_ex": {"type": "float", "cname": "三大法人合計買賣超張數", "unit": "1000 shares", "absorb_field": "institutional_net_buy"},
        },
    },
    "TRAIL/TAQFII": {
        "cname": "試用外資持股資料庫",
        "category": "foreign_holdings",
        "priority": 6,
        "frequency": "daily",
        "entity_field": "coid",
        "period_date_field": "mdate",
        "announcement_date_field": "mdate",
        "pit_safe": True,
        "pit_rationale": "Daily foreign holdings percentage available at post-close.",
        "key_columns": {
            "coid": {"type": "str", "cname": "公司代碼"},
            "mdate": {"type": "date", "cname": "交易日期"},
            "ttl_stk": {"type": "float", "cname": "外資持有股數", "unit": "1000 shares"},
            "inv_pct": {"type": "float", "cname": "外資持股率", "unit": "%", "absorb_field": "foreign_holding_pct"},
        },
    },
    "TRAIL/TAMT": {
        "cname": "試用信用交易/除權息資料庫",
        "category": "margin_dividends",
        "priority": 7,
        "frequency": "quarterly/event",
        "entity_field": "coid",
        "period_date_field": "mdate",
        "announcement_date_field": "edir_d",
        "pit_safe": True,
        "pit_rationale": "Event/announcement date edir_d and ex-dividend date available.",
        "key_columns": {
            "coid": {"type": "str", "cname": "公司代碼"},
            "mdate": {"type": "date", "cname": "除權息/董事會日期"},
            "mt_div1": {"type": "float", "cname": "現金股利", "unit": "NTD/share", "absorb_field": "cash_dividend"},
            "mt_div2": {"type": "float", "cname": "股票股利", "unit": "shares/share", "absorb_field": "stock_dividend"},
        },
    },
    "TRAIL/TAPRCD": {
        "cname": "試用證券交易日行情",
        "category": "market_price",
        "priority": 8,
        "frequency": "daily",
        "entity_field": "coid",
        "period_date_field": "mdate",
        "announcement_date_field": "mdate",
        "pit_safe": True,
        "pit_rationale": "Daily market close data available at end of trading day.",
        "key_columns": {
            "coid": {"type": "str", "cname": "公司代碼"},
            "mdate": {"type": "date", "cname": "交易日期"},
            "open_d": {"type": "float", "cname": "開盤價", "unit": "NTD"},
            "high_d": {"type": "float", "cname": "最高價", "unit": "NTD"},
            "low_d": {"type": "float", "cname": "最低價", "unit": "NTD"},
            "close_d": {"type": "float", "cname": "收盤價", "unit": "NTD"},
            "volume": {"type": "float", "cname": "成交量", "unit": "1000 shares"},
            "amount": {"type": "float", "cname": "成交金額", "unit": "thousand NTD"},
            "per_tej": {"type": "float", "cname": "TEJ本益比", "unit": "multiple", "absorb_field": "pe"},
            "pbr_tej": {"type": "float", "cname": "TEJ股價淨值比", "unit": "multiple", "absorb_field": "pb"},
            "div_yid": {"type": "float", "cname": "殖利率", "unit": "%", "absorb_field": "dividend_yield"},
        },
    },
}


# Mapping of all 22 ABSORB normalized features
ABSORB_FEATURE_MAPPINGS: list[dict[str, Any]] = [
    {
        "absorb_field": "revenue",
        "tej_table": "TRAIL/TASALE",
        "tej_field": "d0001",
        "unit": "thousand NTD",
        "frequency": "monthly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "annd_s",
        "restatement_semantics": "annd_e update tracking",
        "pit_safe": True,
        "status": "supported",
        "notes": "Authoritative monthly revenue announced on annd_s",
    },
    {
        "absorb_field": "revenue_yoy",
        "tej_table": "TRAIL/TASALE",
        "tej_field": "d0005",
        "unit": "%",
        "frequency": "monthly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "annd_s",
        "restatement_semantics": "annd_e update tracking",
        "pit_safe": True,
        "status": "supported",
        "notes": "Year-over-year monthly revenue growth rate",
    },
    {
        "absorb_field": "revenue_mom",
        "tej_table": "TRAIL/TASALE",
        "tej_field": "d0004",
        "unit": "%",
        "frequency": "monthly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "annd_s",
        "restatement_semantics": "annd_e update tracking",
        "pit_safe": True,
        "status": "supported",
        "notes": "Month-over-month revenue growth rate",
    },
    {
        "absorb_field": "revenue_acceleration",
        "tej_table": "TRAIL/TASALE",
        "tej_field": "d0005 delta",
        "unit": "%-points",
        "frequency": "monthly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "annd_s",
        "restatement_semantics": "Calculated as revenue_yoy(t) - revenue_yoy(t-1)",
        "pit_safe": True,
        "status": "supported",
        "notes": "Derived from sequential PIT revenue YoY values",
    },
    {
        "absorb_field": "eps",
        "tej_table": "TRAIL/TAIM1AQ",
        "tej_field": "acc_code:R535",
        "unit": "NTD/share",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003 (via TAIM1AA/TAIM1AQA)",
        "restatement_semantics": "Quarterly filing restatements tracked by publication date",
        "pit_safe": True,
        "status": "supported",
        "notes": "Quarterly recurring earnings per share",
    },
    {
        "absorb_field": "eps_ttm",
        "tej_table": "TRAIL/TAIM1AQ",
        "tej_field": "acc_code:R535 (rolling 4Q sum)",
        "unit": "NTD/share",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "latest a0003",
        "restatement_semantics": "Trailing twelve months sum of quarterly EPS",
        "pit_safe": True,
        "status": "supported",
        "notes": "TTM rolling EPS",
    },
    {
        "absorb_field": "roe",
        "tej_table": "TRAIL/TAIM1AQ",
        "tej_field": "acc_code:R103",
        "unit": "%",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Quarterly filing restatement",
        "pit_safe": True,
        "status": "supported",
        "notes": "Return on equity after tax",
    },
    {
        "absorb_field": "roa",
        "tej_table": "TRAIL/TAIM1AQ",
        "tej_field": "acc_code:R11V",
        "unit": "%",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Quarterly filing restatement",
        "pit_safe": True,
        "status": "supported",
        "notes": "Return on assets comprehensive income",
    },
    {
        "absorb_field": "gross_margin",
        "tej_table": "TRAIL/TAIM1AQ",
        "tej_field": "acc_code:R105",
        "unit": "%",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Quarterly filing restatement",
        "pit_safe": True,
        "status": "supported",
        "notes": "Gross margin ratio",
    },
    {
        "absorb_field": "operating_margin",
        "tej_table": "TRAIL/TAIM1AQ",
        "tej_field": "acc_code:R501",
        "unit": "%",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Quarterly filing restatement",
        "pit_safe": True,
        "status": "supported",
        "notes": "Operating income margin ratio",
    },
    {
        "absorb_field": "debt_ratio",
        "tej_table": "TRAIL/TAIM1AQ",
        "tej_field": "acc_code:R504",
        "unit": "%",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Quarterly filing restatement",
        "pit_safe": True,
        "status": "supported",
        "notes": "Total liabilities to equity ratio",
    },
    {
        "absorb_field": "current_ratio",
        "tej_table": "TRAIL/TAIM1AQ",
        "tej_field": "acc_code:R406",
        "unit": "%",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Quarterly filing restatement",
        "pit_safe": True,
        "status": "supported",
        "notes": "Current assets to current liabilities ratio",
    },
    {
        "absorb_field": "operating_cash_flow",
        "tej_table": "TRAIL/TAIM1A",
        "tej_field": "acc_code:C001",
        "unit": "thousand NTD",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Quarterly filing restatement",
        "pit_safe": True,
        "status": "supported",
        "notes": "Cash flows from operating activities",
    },
    {
        "absorb_field": "free_cash_flow",
        "tej_table": "TRAIL/TAIM1A",
        "tej_field": "acc_code:C001 - CapEx",
        "unit": "thousand NTD",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Operating cash flow minus capital expenditures",
        "pit_safe": True,
        "status": "supported",
        "notes": "Free cash flow derived from cash flow statements",
    },
    {
        "absorb_field": "book_value",
        "tej_table": "TRAIL/TAIM1A",
        "tej_field": "acc_code:2000",
        "unit": "thousand NTD",
        "frequency": "quarterly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "a0003",
        "restatement_semantics": "Quarterly filing restatement",
        "pit_safe": True,
        "status": "supported",
        "notes": "Total shareholders equity",
    },
    {
        "absorb_field": "pe",
        "tej_table": "TRAIL/TAPRCD",
        "tej_field": "per_tej",
        "unit": "multiple",
        "frequency": "daily",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "mdate",
        "restatement_semantics": "Daily official close metric",
        "pit_safe": True,
        "status": "supported",
        "notes": "TEJ price to earnings ratio",
    },
    {
        "absorb_field": "pb",
        "tej_table": "TRAIL/TAPRCD",
        "tej_field": "pbr_tej",
        "unit": "multiple",
        "frequency": "daily",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "mdate",
        "restatement_semantics": "Daily official close metric",
        "pit_safe": True,
        "status": "supported",
        "notes": "TEJ price to book ratio",
    },
    {
        "absorb_field": "dividend_yield",
        "tej_table": "TRAIL/TAPRCD",
        "tej_field": "div_yid",
        "unit": "%",
        "frequency": "daily",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "mdate",
        "restatement_semantics": "Daily official close metric",
        "pit_safe": True,
        "status": "supported",
        "notes": "Annualized dividend yield",
    },
    {
        "absorb_field": "foreign_net_buy",
        "tej_table": "TRAIL/TATINST1",
        "tej_field": "qfii_ex1",
        "unit": "1000 shares",
        "frequency": "daily",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "mdate",
        "restatement_semantics": "Daily post-close trading summary",
        "pit_safe": True,
        "status": "supported",
        "notes": "Net foreign institutional share purchases/sales",
    },
    {
        "absorb_field": "institutional_net_buy",
        "tej_table": "TRAIL/TATINST1",
        "tej_field": "ttl_ex",
        "unit": "1000 shares",
        "frequency": "daily",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "mdate",
        "restatement_semantics": "Daily post-close trading summary",
        "pit_safe": True,
        "status": "supported",
        "notes": "Total three major institutional investors net purchase/sale",
    },
    {
        "absorb_field": "margin_balance",
        "tej_table": "TRAIL/TAMT",
        "tej_field": "amt_tt",
        "unit": "thousand NTD",
        "frequency": "event/daily",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "mdate",
        "restatement_semantics": "Post-close margin trading total",
        "pit_safe": True,
        "status": "supported",
        "notes": "Margin trading total balance amount",
    },
    {
        "absorb_field": "director_holdings",
        "tej_table": "TRAIL/TAATT",
        "tej_field": "fld012",
        "unit": "%",
        "frequency": "monthly",
        "entity_id": "coid",
        "period_date": "mdate",
        "available_at_source": "mdate",
        "restatement_semantics": "None",
        "pit_safe": False,
        "status": "unsupported",
        "notes": "Table TRAIL/TAATT returned 0 records in current trial entitlement.",
    },
]


def generate_schema_evidence_report() -> dict[str, Any]:
    """Generate structured schema evidence and feature mapping document."""
    return {
        "schema_version": 1,
        "kind": "absorb-tej-schema-evidence",
        "table_count": len(TEJ_TABLE_SCHEMAS),
        "tables": TEJ_TABLE_SCHEMAS,
        "feature_count": len(ABSORB_FEATURE_MAPPINGS),
        "features": ABSORB_FEATURE_MAPPINGS,
        "pit_safe_features": [
            f["absorb_field"] for f in ABSORB_FEATURE_MAPPINGS if f.get("pit_safe")
        ],
        "unsupported_features": [
            f["absorb_field"] for f in ABSORB_FEATURE_MAPPINGS if not f.get("pit_safe")
        ],
    }
